import { palette } from './palette';
import type { AppTheme, ThemeBorderRadius, ThemeSpacing } from './types';

const spacing: ThemeSpacing = {
  extraSmall: 4,
  small: 8,
  medium: 16,
  large: 24,
  extraLarge: 32,
};

const borderRadius: ThemeBorderRadius = {
  small: 4,
  medium: 8,
  large: 16,
  round: 999,
};

export const lightTheme: AppTheme = {
  mode: 'light',
  colors: {
    background: palette.lightBackground,
    surface: palette.lightSurface,
    surfaceSecondary: palette.lightSurfaceSecondary,
    surfaceElevated: palette.lightSurface,
    primary: palette.lightStructuralGreen,
    primaryStrong: palette.lightStructuralGreenStrong,
    primarySoft: palette.lightStructuralGreenSoft,
    text: palette.lightText,
    textSecondary: palette.lightTextSecondary,
    textOnPrimary: palette.lightTextOnGreen,
    border: palette.lightBorder,
    borderStrong: palette.lightBorderStrong,
    accent: palette.lightGold,
    accentStrong: palette.lightGoldStrong,
    accentSoft: palette.lightGoldSoft,
    warning: palette.lightWarning,
    warningBackground: palette.lightWarningBackground,
    danger: palette.lightDanger,
    dangerBackground: palette.lightDangerBackground,
    success: palette.lightSuccess,
    successBackground: palette.lightSuccessBackground,
    successActionBackground: palette.lightStructuralGreen,
    successActionText: palette.lightTextOnGreen,
    disabled: palette.lightDisabled,
    disabledText: palette.lightDisabledText,
    overlay: 'rgba(4, 2, 0, 0.48)',
    shadow: 'rgba(4, 2, 0, 0.22)',
    inputBackground: palette.lightSurface,
    inputBorder: palette.lightBorderStrong,
    placeholder: palette.lightPlaceholder,
    progressTrack: palette.lightSurfaceSecondary,
    progressFill: palette.lightStructuralGreen,
    circularProgressTrack: palette.lightBorderStrong,
    circularProgressFill: palette.lightStructuralGreen,
    circularProgressAccentTrack: palette.lightBorderStrong,
    circularProgressAccentFill: palette.lightStructuralGreen,
    cardAccent: palette.lightSurface,
    cardAccentBorder: palette.lightBorder,
    cardAccentText: palette.lightText,
    cardAccentIcon: palette.lightTextSecondary,
    cardAccentMuted: palette.lightBorder,
    selectedBackground: palette.lightStructuralGreenSoft,
    selectedBorder: palette.lightStructuralGreen,
    focusRing: palette.lightGoldStrong,
    navigationBackground: palette.lightStructuralGreenStrong,
    navigationText: palette.lightTextOnGreen,
    navigationTextSecondary: '#D7D0C2',
    textPrimary: palette.lightText,
    primaryContrast: palette.lightTextOnGreen,
    drawerBackground: palette.lightStructuralGreenStrong,
    drawerActiveBackground: palette.lightStructuralGreenSoft,
    drawerActiveText: palette.lightText,
  },
  spacing,
  borderRadius,
};

export const darkTheme: AppTheme = {
  mode: 'dark',
  colors: {
    background: palette.darkBackground,
    surface: palette.darkSurface,
    surfaceSecondary: palette.darkSurfaceSecondary,
    surfaceElevated: palette.darkSurfaceElevated,
    primary: palette.darkStructuralGreen,
    primaryStrong: palette.darkStructuralGreenStrong,
    primarySoft: palette.darkStructuralGreenSoft,
    text: palette.darkText,
    textSecondary: palette.darkTextSecondary,
    textOnPrimary: palette.darkTextOnGreen,
    border: palette.darkBorder,
    borderStrong: palette.darkBorderStrong,
    accent: palette.darkGold,
    accentStrong: palette.darkGoldStrong,
    accentSoft: palette.darkGoldSoft,
    warning: palette.darkWarning,
    warningBackground: palette.darkWarningBackground,
    danger: palette.darkDanger,
    dangerBackground: palette.darkDangerBackground,
    success: palette.darkSuccess,
    successBackground: palette.darkSuccessBackground,
    successActionBackground: palette.darkStructuralGreen,
    successActionText: palette.darkTextOnGreen,
    disabled: palette.darkDisabled,
    disabledText: palette.darkDisabledText,
    overlay: 'rgba(4, 2, 0, 0.72)',
    shadow: 'rgba(4, 2, 0, 0.64)',
    inputBackground: palette.darkSurfaceSecondary,
    inputBorder: palette.darkBorderStrong,
    placeholder: palette.darkPlaceholder,
    progressTrack: palette.darkSurfaceElevated,
    progressFill: palette.darkSuccess,
    circularProgressTrack: palette.darkCircularTrack,
    circularProgressFill: palette.darkSuccess,
    circularProgressAccentTrack: palette.darkCircularAccentTrack,
    circularProgressAccentFill: palette.darkSuccess,
    cardAccent: palette.darkSurface,
    cardAccentBorder: palette.darkCircularAccentTrack,
    cardAccentText: palette.darkGold,
    cardAccentIcon: palette.darkGold,
    cardAccentMuted: palette.darkGoldSoft,
    selectedBackground: palette.darkStructuralGreenSoft,
    selectedBorder: palette.darkGold,
    focusRing: palette.darkGoldStrong,
    navigationBackground: palette.darkStructuralGreenStrong,
    navigationText: palette.darkTextOnGreen,
    navigationTextSecondary: palette.darkTextSecondary,
    textPrimary: palette.darkText,
    primaryContrast: palette.darkTextOnGreen,
    drawerBackground: palette.darkStructuralGreenStrong,
    drawerActiveBackground: palette.darkStructuralGreenSoft,
    drawerActiveText: palette.darkTextOnGreen,
  },
  spacing,
  borderRadius,
};
