import { router, type Href } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { ReactNode } from 'react';
import { AppText as Text } from './app-text';
import { SpiritAshProgressButton } from './spirit-ash-progress-button';
import { getSpiritAshById } from '../data';
import { useApp } from '../hooks/use-app';

export function SpiritAshDetailScreen({ id }: { readonly id: string }) {
  const app = useApp(); const entry = getSpiritAshById(id); const isCollected = Boolean(entry && app.collectedSpiritAshIds.includes(entry.id));
  if (!entry) return <SafeAreaView style={[styles.center, { backgroundColor: app.theme.colors.background }]}><Text variant="display" style={{ color: app.theme.colors.textPrimary }}>Spirit Ash not found</Text><Pressable accessibilityRole="button" onPress={() => router.canGoBack() ? router.back() : router.replace('/spirit-ashes' as Href)}><Text style={{ color: app.theme.colors.primary }}>Back to Spirit Ashes</Text></Pressable></SafeAreaView>;
  return <SafeAreaView style={[styles.screen, { backgroundColor: app.theme.colors.background }]}><ScrollView contentContainerStyle={[styles.content, { gap: app.theme.spacing.medium, padding: app.theme.spacing.large }]}><Text variant="display" accessibilityRole="header" style={{ color: app.theme.colors.textPrimary }}>{entry.name}</Text><Section title="Origin"><Text style={{ color: app.theme.colors.textPrimary }}>{entry.contentPack === 'base-game' ? 'Base game' : 'Shadow of the Erdtree'}</Text></Section><Section title="Location"><Text style={{ color: app.theme.colors.textPrimary }}>{entry.primaryLocation}</Text></Section><Section title="Acquisition"><Text style={{ color: app.theme.colors.textPrimary }}>{entry.primaryAcquisition}</Text>{entry.acquisitionMethods.map((method, index) => <View key={`${entry.id}-${index}`}><Text style={{ color: app.theme.colors.textSecondary }}>{index + 1}. {method.source}</Text>{method.steps.map((step, stepIndex) => <Text key={step} style={{ color: app.theme.colors.textSecondary }}>{stepIndex + 1}. {step}</Text>)}</View>)}</Section><Section title="Summon cost"><Text style={{ color: app.theme.colors.textPrimary }}>{entry.summonCost.amount === null ? 'Cost not documented' : `${entry.summonCost.amount} ${entry.summonCost.type.toUpperCase()}`}</Text></Section><Section title="Technical data"><Text style={{ color: app.theme.colors.textPrimary }}>Upgrade material: {entry.upgradeType === 'grave-glovewort' ? 'Grave Glovewort' : entry.upgradeType === 'ghost-glovewort' ? 'Ghost Glovewort' : 'Not upgradable'}</Text>{entry.numberSummoned !== null ? <Text style={{ color: app.theme.colors.textPrimary }}>Number summoned: {entry.numberSummoned}</Text> : null}{entry.legendary ? <Text style={{ color: app.theme.colors.accent }}>Legendary</Text> : null}</Section><Section title="Collection status"><Text style={{ color: isCollected ? app.theme.colors.success : app.theme.colors.textSecondary }}>{isCollected ? 'Collected' : 'Not collected'}</Text><SpiritAshProgressButton id={entry.id} isCollected={isCollected} name={entry.name} /></Section></ScrollView></SafeAreaView>;
}
function Section({ title, children }: { readonly title: string; readonly children: ReactNode }) { const { theme } = useApp(); return <View style={{ backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.borderRadius.medium, borderWidth: 1, gap: theme.spacing.small, padding: theme.spacing.medium }}><Text style={{ color: theme.colors.accent, fontWeight: '800' }}>{title}</Text>{children}</View>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { paddingBottom: 48 }, center: { alignItems: 'center', flex: 1, gap: 16, justifyContent: 'center' } });
